### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by klev-sm** [klev-sm/unsplash-api#1]
# Image Uploader
- [x] Set up multer
- [x] Upload image to temporary folder
- [x] Return url from upload
- [x] Upload image link to database
- [x] When deleting/editing image from database, upload on Cloudinary too
- [x] Delete images from temp folder when uploading and saving to database
- [x] Treat/improve image before save to Cloudinary and database
- [x] Test error handling
- [x] Add subtitle to images
- [x] Edit route to update images and subtitles
    - [x]  Scenario 1: Update just the subtitle
    - [x]  Scenario 2: Update just the image
    - [x]  Scenario 3: Update both
- [x] Change the docs to new subtitle feature.
- [x] Delete temp file in folder on error
- [x] Change the folder that image is being saved on Cloudinary
- [x] Improve Multer boilerplate
- [x] Create helpers to improve JSON responses
- [x] Comment and document code

# User Authentication App
- [x] Create User routes
- [x] Allow certain routes to certain users 
- [x] Login Route
- [x] Reference users and images
- [x] Change the docs of .env file
- [x] Make the database save the publicId of the image
- [ ] Improve error responses.
- [ ] Improve code
- [ ] Normalize the database (user profile pictures and images)
- [ ] Social Login
